import type { Metadata } from "next";
import satoshi from "@/app/fonts";
import "./globals.css";
import { StateProvider } from "../app/contexts/StateProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${satoshi.variable}`}>
      <body>
      <StateProvider>{children}</StateProvider>
      </body>
    </html>
  );
}
